# mlflow-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mlflow-secret
  namespace: mlflow
type: Opaque
stringData:
  # 数据库密码
  MLFLOW_DB_PASSWORD: mlflow123
  # MinIO / S3 凭证
  AWS_ACCESS_KEY_ID: minioadmin
  AWS_SECRET_ACCESS_KEY: minioadmin123
