apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
      - name: mlflow
        image: docker-registry:81/harbor-mlflow/mlflow:v2.9.2-arm
        command: ["mlflow"]
        args:
        - server
        - --host=0.0.0.0
        - --port=5000
        - --backend-store-uri=mysql+pymysql://mlflow:mlflow@192.168.246.151:13306/mlflow
        - --default-artifact-root=s3://mlflow/
        ports:
        - containerPort: 5000
