apiVersion: v1
kind: ConfigMap
metadata:
  name: test2-config
  labels:
    app: test2-config
data:
  test2.config: |
    api_token: 123456789
    api_url: https://api.example.com
    api_port: 443
    api_path: /api/v1
    api_timeout: 30
    api_retries: 3

---
apiVersion: v1
kind: Pod
metadata:
  name: use-configmap-test3
  labels:
    name: use-configmap-test3
spec:
  containers:
    - name: use-configmap-test3
      image: nginx
      env:
        - name: TEST2_CONFIG
          value: "root_password"
      volumeMounts:
        - name: config-volume
          mountPath: /root/test2/test2.config
          subPath: test2.config

  volumes:
    - name: config-volume
      configMap:
        name: test2-config